ToDo App/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("comments/in/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path("update/<int:pk>/",views.UpdatePost.as_view(),name="update")
]

ToDo App/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('comments/',include("comments.urls", namespace="comments"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ToDo App/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    name = models.CharField(max_length = 256)
    status = models.CharField(max_length = 256, null=True)
    deadline = models.CharField(max_length = 256, null=True)
    priority = models.IntegerField()
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"username": self.user.username,"pk": self.pk})

    class Meta:
        ordering = ["priority"]
        unique_together = ["user", "name"]

ToDo App/posts/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("name", "status","deadline","priority","group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

ToDo App/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ("user", "group")

class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

class CreatePost(LoginRequiredMixin, generic.CreateView):
    fields = ('name','status','deadline','priority','group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,  SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

class UpdatePost(LoginRequiredMixin,  SelectRelatedMixin,generic.UpdateView):
    fields = ('name','status','priority','deadline')
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

ToDo App/posts/templates/posts/_post.html
<td>
	<h5><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.name|safe }}</a></h5>
</td>
<td>
	<h5>{{ post.status|safe }}</h5>
</td>
<td>
	<h5>{{ post.deadline|safe }}</h5>
</td>
<td>
	<h5>{{ post.priority }}</h5>
</td>
<td>
	{% if user.is_authenticated and post.user == user and not hide_delete %}
	<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
	<span class="fa fa-remove text-danger" aria-hidden="true"></span>
	<span class="text-danger icon-label">Delete</span>
	</a>
	{% endif %}
</td>
<td>
	{% if user.is_authenticated and post.user == user %}
	<a href="{% url 'posts:update' pk=post.pk %}" title="update" class="btn btn-simple">
	<span class="text-warning icon-label">Edit</span>
	</a>
	{% endif %}
</td>

ToDo App/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
		{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post %}{% endblock %}
{% endblock %}

ToDo App/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this task?</h3>

<div class="posts" style="margin-top:30px;">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div

<form method="POST" style="margin-top:30px;">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' pk=post.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

ToDo App/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
  <table class="table table-striped" style="margin-top: 20px;">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">Deadline</th>
        <th scope="col">Priority</th>
        <th scope="col">Delete</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>

    <tbody>

    <tr>
    {% include "posts/_post.html" %}
    </tr>

    </tbody>
  </table>

  <div class="container">
  <div class="row">
  	{% if post.comments.count == 0 %}
  	<h2>No comments in this task yet!</h2>
    <hr></hr>
  	{% else %}
      <h6>Comments: </h6>

      <table class="table table-striped" style="margin-top: 20px;">
      <thead>
        <tr>
          <th>
            Comment message
          </th>
          <th>
            Files
          </th>
          <th>
            Delete
          </th>
        </tr>
      </thead>
  		{% for comment in post.comments.all %}
      <tbody>
        <tr>
          <td>
            {{ comment.message }}
          </td>
          <td>
            {% if comment.files %}
              <a href="{{ comment.files.url }}" class="btn btn-sm btn-ptimary">Download</a>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'comments:delete' pk=comment.pk %}" title="delete" class="btn btn-simple">
          	<span class="fa fa-remove text-danger" aria-hidden="true"></span>
          	<span class="text-danger icon-label">Delete</span>
          	</a>
          </td>
          </tr>
      </tbody>
  		{% endfor %}
      </table>

  	{% endif %}

    {% if user.is_authenticated %}
    <a href="{% url 'comments:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create New Comment!</a>
  	{% endif %}

  </div>
  </div>
<!-- </div> -->
{% endblock %}

ToDo App/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
{% if not form.instance.pk %}
<h4>Create New Task</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Create</button>
	{% endbuttons %}
</form>

{% else%}
<h4>Update Task</h4>
<form method="POST" action="{% url 'posts:update' pk=post.pk %}">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Update</button>
	{% endbuttons %}
</form>

{% endif %}
{% endblock %}

ToDo App/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="row">
	{% if posts.count == 0 %}
	<h2>No Tasks yet!</h2>
	{% else %}
	<h2 style="color: #4fc930;"> List of all the tasks from every Project </h2>
  <table class="table table-striped" style="margin-top: 20px;">
    <thead>
      <tr>
        <th scope="col">Name</th>
				<th scope="col">Status</th>
				<th scope="col">Deadline</th>
				<th scope="col">Priority</th>
        <th scope="col">Delete</th>
        <th scope="col">Edit</th>
				<th scope="col">Project</th>
      </tr>
    </thead>

    <tbody>
		{% for post in post_list %}
    <tr>
			{% include "posts/_post.html" %}
			<td>
				{{ post.group.name }}
			</td>
    </tr>
		{% endfor %}
    </tbody>
  </table>

	{% endif %}

	{% if user.is_authenticated %}
  <a href="{% url 'posts:create' %}" class="btn btn-warning" role="button" style="margin-top:40px;"><span class="fa fa-plus"></span> Create New Task!</a>
	{% endif %}
</div>
{% endblock %}

ToDo App/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>{{ post_user.username }}</h1>
	<p>Task History</p>
</div>
{% endblock %}

{% block post_content %}
<table class="table table-striped" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
      <th scope="col">Deadline</th>
      <th scope="col">Priority</th>
      <th scope="col">Delete</th>
      <th scope="col">Edit</th>
      <th scope="col">Project</th>
    </tr>
  </thead>

<div class="col-md-8">
	    {% for post in post_list %}
		    {% include "posts/_post.html" %}
        <td>
  				{{ post.group.name }}
  			</td>
	    {% endfor %}

</div>
</table>
{% endblock %}