ToDo App/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<int:pk>/",views.SingleGroup.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeleteGroup.as_view(),name="delete"),
    path("update/<int:pk>/",views.UpdateGroup.as_view(),name="update")
]

ToDo App/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("comments/in/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path("update/<int:pk>/",views.UpdatePost.as_view(),name="update")
]

ToDo App/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('comments/',include("comments.urls", namespace="comments"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ToDo App/groups/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["name"]

ToDo App/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class DeleteGroup(generic.DeleteView):
    model = Group
    success_url = reverse_lazy("groups:all")

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Project Deleted")
        return super().delete(*args, **kwargs)

class UpdateGroup(generic.UpdateView):
    fields = ("name", "description")
    model = Group

ToDo App/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

ToDo App/groups/templates/groups/group_confirm_delete.html
{% extends "groups/group_base.html" %}

{% block group_content %}
<h3>Are you sure you want to delete this group?</h3>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'groups:all' %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

ToDo App/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="container">
  <h1 >{{group.name}} Tasks</h1>
</div>
{% endblock %}

{% block group_content %}
<div class="container">
<div class="row">
	{% if group.posts.count == 0 %}
	<h2>No Tasks in this group yet!</h2>
	{% else %}

  <table class="table table-striped" style="margin-top: 20px;">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">Deadline</th>
        <th scope="col">Priority</th>
        <th scope="col">Delete</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>

    <tbody>
		{% for post in group.posts.all %}
    <tr>
			{% include "posts/_post.html" %}
    </tr>
		{% endfor %}
    </tbody>
  </table>

	{% endif %}

  {% if user.is_authenticated %}
  <a href="{% url 'posts:create' %}" class="btn btn-warning" role="button" style="margin-top:40px;"><span class="fa fa-plus"></span> Create New Task!</a>
	{% endif %}

</div>
</div>
{% endblock %}

ToDo App/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
<div class="container">
  {% if not form.instance.pk %}
    <h4>Create A New Project</h4>
    <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
    	{% csrf_token %}
    	{% bootstrap_form form %}
      {% buttons %}
    		<button type="submit" class="btn btn-primary btn-large">Create</button>
    	{% endbuttons %}
    </form>

  {% else %}
  <h4>Update Project</h4>
  <form method="POST" action="{% url 'groups:update' pk=group.pk %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary btn-large">Update</button>
    {% endbuttons %}
  </form>
 {% endif %}

</div>
{% endblock %}

ToDo App/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		<h2 style="margin-top:20px;">Welcome to the Projects Page!</h2>
	</div>
		{% if user.is_authenticated %}
		<div class="content">
		<h2 style="margin-top:40px;">
			Welcome
			<a href="{% url 'posts:for_user' username=user.username %}">{{user.username }}</a>
		</h2>
	</div>
	<a href="{% url 'groups:create' %}" class="btn btn-warning" role="button" style="margin-top:40px;"><span class="fa fa-plus"></span> Create New Project!</a>
	{% endif %}

</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<h2 style="margin-top: 0px; margin-bottom:20px;"> Project List </h2>
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'groups:single' pk=group.pk %}"
		class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description|safe }}</p>
			<div class="justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> Task{{ group.posts.count|pluralize }}</small>
			<span></span><span></span>
			{% if user.is_authenticated %}
			<a href="{% url 'groups:delete' pk=group.pk %}" class="btn btn-danger btn-sm" role="button"><span class="fa fa-remove"></span> Delete</a>
			<a href="{% url 'groups:update' pk=group.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
			{% endif %}
			</div>
		</a>
		<br>
		{% endfor %}
	</div>
</div>
{% endblock %}